### ISSUE TITLE
Memento test failure

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#302]
I've recently enabled `MementoTimeGateTests` for my impl and was truly surprised to find the following failure:
```
-------------------------------------------------------------------------------
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.357 s <<< FAILURE! - in edu.si.trellis.cassandra.MementoTimeGateIT
testBadTimeGateRequest  Time elapsed: 0.062 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Check for an error response ==> expected: <CLIENT_ERROR> but was: <SUCCESSFUL>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:54)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:184)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:519)
	at org.trellisldp.test.MementoTimeGateTests.testBadTimeGateRequest(MementoTimeGateTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
because [that code](https://github.com/trellis-ldp/trellis/blob/master/components/test/src/main/java/org/trellisldp/test/MementoTimeGateTests.java#L125) is:
```
    @Test
    @DisplayName("Test bad timegate request")
    default void testBadTimeGateRequest() {
        try (final Response res = target(getResourceLocation()).request()
                .header(ACCEPT_DATETIME, "unparseable date string").get()) {
            assertEquals(CLIENT_ERROR, res.getStatusInfo().getFamily(), "Check for an error response");
        }
    }
```
It's not at all clear to me how my impl could end up being asked for a Memento, much less offering one. Any thoughts?

**Comment by acoburn** [comment]
Can you verify that the `TrellisHttpFilter` class has been loaded? That RequestFilter _should_ throw a `CLIENT_ERROR` [here](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/TrellisHttpFilter.java#L71-L72), given that input value.

**Comment by ajs6f** [comment]
Nailed it in one.
